#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains
# the string Ceci n'est pas une page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# Create index page
echo 'Holberton School' > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Add redirect configuration
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Add custom 404 page configuration
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart
